# This file was generated by GoReleaser. DO NOT EDIT.
cask "catalog" do
  version "0.1.11"

  on_macos do
    on_intel do
      sha256 "7ef16a5c1b328ef1302b1cc7d082b40fa9f35fd77db313495a72ab76049a690a"
      url "https://github.com/westarete/catalog/releases/download/v#{version}/catalog_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "4828fc4ea9b0a18c3cfcbb6ca0240147ef974b8d6e889e7e1379897269fd598b"
      url "https://github.com/westarete/catalog/releases/download/v#{version}/catalog_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "a1a1d0aec9285bc044b31f4f13889d378c4a50db187b36b499ea7345cb84bfff"
      url "https://github.com/westarete/catalog/releases/download/v#{version}/catalog_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "b3ec8324d6ec23f733300e5f954b9c79797a88e43d02a53452ea25b9ea113607"
      url "https://github.com/westarete/catalog/releases/download/v#{version}/catalog_linux_arm64.tar.gz"
    end
  end

  name "catalog"
  desc "Generates and maintains .catalog.md for AI agent context loading"
  homepage "https://github.com/westarete/catalog"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "catalog"

  zap trash: [
      "~/.config/catalog",
    ]

end
