# This file was generated by GoReleaser. DO NOT EDIT.
cask "catalog" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "76c0635c670f74f93472915fea718a47c53657ec8802693004611ce0cb5de03f"
      url "https://github.com/westarete/catalog/releases/download/v#{version}/catalog_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "8c7eccbef1667d0b4792f3223e0c214189fff7e20d864ed2faf572c9efa6820d"
      url "https://github.com/westarete/catalog/releases/download/v#{version}/catalog_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "e93aa89250bdc594402393a0ff8439d24bffec115f6e21f8d66de763f8eba284"
      url "https://github.com/westarete/catalog/releases/download/v#{version}/catalog_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "4c3a841de0a24477a0b5df2be842763a1b3d16364806b25c10b1ae498d80603c"
      url "https://github.com/westarete/catalog/releases/download/v#{version}/catalog_linux_arm64.tar.gz"
    end
  end

  name "catalog"
  desc "Generates and maintains CATALOG.md — a behavior file that tells an AI agent when to pull each document into context."
  homepage "https://github.com/westarete/catalog"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "catalog"

  # No zap stanza required

end
