# This file was generated by GoReleaser. DO NOT EDIT.
cask "catalog" do
  version "0.3.0"

  on_macos do
    on_arm do
      sha256 "18f617429d8ef0955cacf7c7b5fa80736850bf75abcaa5d2ec4b3b129adb0b8c"
      url "https://github.com/westarete/catalog/releases/download/v#{version}/catalog_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "f680c543ec9737fcf49bab18ea894dd19f5ba8b57b7e84bc8e54e5d8d8cf0a5c"
      url "https://github.com/westarete/catalog/releases/download/v#{version}/catalog_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "a4b59becc4f220df01303e0278585559cd1e85ab2d276779c949068c4ff52776"
      url "https://github.com/westarete/catalog/releases/download/v#{version}/catalog_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "6696618ccf0522ef6c4dd4ea30528a9f8c9925df0cbf4c5f3f6a789aa720605f"
      url "https://github.com/westarete/catalog/releases/download/v#{version}/catalog_linux_amd64.tar.gz"
    end
  end

  name "catalog"
  desc "Generates and maintains .catalog.md for AI agent context loading"
  homepage "https://github.com/westarete/catalog"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "catalog"

  zap trash: [
      "~/.config/catalog",
    ]

end
